### ISSUE TITLE
ipc_helper barf

### ISSUE THREAD

**Issue by GGunnison** [MIT-STARLab/CLICK-A-RPi#17]
Sep 20 18:51:53 click python[297]: Traceback (most recent call last):
Sep 20 18:51:53 click python[297]:   File "/root/test/general_functionality_test.py", line 19, in <module>
Sep 20 18:51:53 click python[297]:     fpga = ipc_helper.FPGAClientInterface()
Sep 20 18:51:53 click python[297]:   File "/root/lib/ipc_helper.py", line 38, in __init__
Sep 20 18:51:53 click python[297]:     self.write_reg(127,'')
Sep 20 18:51:53 click python[297]:   File "/root/lib/ipc_helper.py", line 135, in write_reg
Sep 20 18:51:53 click python[297]:     return future.wait()
Sep 20 18:51:53 click python[297]:   File "/root/lib/ipc_helper.py", line 62, in wait
Sep 20 18:51:53 click python[297]:     if not self.valid: self.handler._receive(self)
Sep 20 18:51:53 click python[297]:   File "/root/lib/ipc_helper.py", line 179, in _receive
Sep 20 18:51:53 click python[297]:     assert pck.rq_number == current_fut.token
Sep 20 18:51:53 click python[297]: AssertionError

This happens sporadically and I'm not sure exactly why. This happened at the beginning of a self test crashing the script

**Comment by PCSerra** [comment]
A request was received but was not matching the one expected. So:

1. An FPGA answer packet was inserted
2. An FPGA request was dropped
3. The FPGA server answered out of order

**Comment by PCSerra** [comment]
There is also a very slight chance of 32bit ID collision but shout be on the order of > 1/10k.
